//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.05 at 01:33:51 AM CEST 
//


package pl.coderstrust.soap.bindingclasses;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.coderstrust.soap.bindingclasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InvoiceId_QNAME = new QName("http://project-10-ewa-januss-wieslaw", "id");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.coderstrust.soap.bindingclasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SaveInvoiceRequest }
     * 
     */
    public SaveInvoiceRequest createSaveInvoiceRequest() {
        return new SaveInvoiceRequest();
    }

    /**
     * Create an instance of {@link Invoice }
     * 
     */
    public Invoice createInvoice() {
        return new Invoice();
    }

    /**
     * Create an instance of {@link UpdateInvoiceRequest }
     * 
     */
    public UpdateInvoiceRequest createUpdateInvoiceRequest() {
        return new UpdateInvoiceRequest();
    }

    /**
     * Create an instance of {@link DeleteInvoiceRequest }
     * 
     */
    public DeleteInvoiceRequest createDeleteInvoiceRequest() {
        return new DeleteInvoiceRequest();
    }

    /**
     * Create an instance of {@link DeleteAllInvoicesRequest }
     * 
     */
    public DeleteAllInvoicesRequest createDeleteAllInvoicesRequest() {
        return new DeleteAllInvoicesRequest();
    }

    /**
     * Create an instance of {@link GetAllInvoicesRequest }
     * 
     */
    public GetAllInvoicesRequest createGetAllInvoicesRequest() {
        return new GetAllInvoicesRequest();
    }

    /**
     * Create an instance of {@link GetInvoiceRequest }
     * 
     */
    public GetInvoiceRequest createGetInvoiceRequest() {
        return new GetInvoiceRequest();
    }

    /**
     * Create an instance of {@link GetInvoiceByNumberRequest }
     * 
     */
    public GetInvoiceByNumberRequest createGetInvoiceByNumberRequest() {
        return new GetInvoiceByNumberRequest();
    }

    /**
     * Create an instance of {@link InvoiceResponse }
     * 
     */
    public InvoiceResponse createInvoiceResponse() {
        return new InvoiceResponse();
    }

    /**
     * Create an instance of {@link ResponseBase }
     * 
     */
    public ResponseBase createResponseBase() {
        return new ResponseBase();
    }

    /**
     * Create an instance of {@link InvoicesResponse }
     * 
     */
    public InvoicesResponse createInvoicesResponse() {
        return new InvoicesResponse();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Company }
     * 
     */
    public Company createCompany() {
        return new Company();
    }

    /**
     * Create an instance of {@link InvoiceEntry }
     * 
     */
    public InvoiceEntry createInvoiceEntry() {
        return new InvoiceEntry();
    }

    /**
     * Create an instance of {@link EntriesList }
     * 
     */
    public EntriesList createEntriesList() {
        return new EntriesList();
    }

    /**
     * Create an instance of {@link InvoicesList }
     * 
     */
    public InvoicesList createInvoicesList() {
        return new InvoicesList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "http://project-10-ewa-januss-wieslaw", name = "id", scope = Invoice.class)
    public JAXBElement<Long> createInvoiceId(Long value) {
        return new JAXBElement<Long>(_InvoiceId_QNAME, Long.class, Invoice.class, value);
    }

}
